import Head from "next/head";
import React from "react";

const Header = () => {
  return (
    <>
      <Head>
        <title>Braham Prakash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header></header>
    </>
  );
};

export default Header;
