import Head from "next/head";
import Image from "next/image";
import React, { useState, useEffect } from "react";
import SocialIcons from "./common/SocialIcons";

let heightWidthClass = ``;
const Header = () => {
  const [hideHeader, setHideHeader] = useState(true);

  const handleHamClick = () => {
    setHideHeader((prevValue) => !!!prevValue);
  };

  const handleHeaderClose = () => {
    setHideHeader(() => true);
  };

  const hamIconSizeClasses = `w-7 h-7`;

  return (
    <>
      <Head>
        <title>Braham Prakash</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button
        className={`menu-icon-container ${hamIconSizeClasses} fixed z-[9999999] m-4 overflow-hidden`}
        type="button"
        onClick={handleHamClick}
      >
        <div
          className={`icon-ham-menu-cross relative ${hamIconSizeClasses} transition-transform ${
            hideHeader ? "-translate-y-full" : ""
          }`}
        >
          <Image
            src="/icon-ham-menu-cross.svg"
            layout="fill"
            alt="ham menu cross icon"
          />
        </div>
        <div
          className={`icon-ham-menu relative ${hamIconSizeClasses} transition-transform ${
            hideHeader ? "-translate-y-full" : ""
          }`}
        >
          <Image src="/icon-ham-menu.svg" layout="fill" alt="ham menu icon" />
        </div>
      </button>

      <header
        className={`fixed inset-0 z-[999999] grid min-h-screen grid-rows-[1fr_auto] place-content-center text-center transition-all ${
          hideHeader ? "-translate-y-full opacity-0" : "opacity-100"
        }`}
      >
        <nav className="font-laila text-custom-white-extra-light grid place-content-center space-y-3 text-3xl font-semibold">
          <a onClick={handleHeaderClose} className="" href="#hero">
            Home
          </a>
          <a onClick={handleHeaderClose} className="" href="#works">
            My Works
          </a>
          <a onClick={handleHeaderClose} className="" href="#contact">
            Contact Me
          </a>
        </nav>
        <div className="-translate-y-8">
          <SocialIcons />
        </div>
      </header>
    </>
  );
};

export default Header;
